apiVersion: v1
kind: PersistentVolume
metadata:
  name: deepseek-rag-logs-pv
  labels:
    type: local
    app: deepseek-rag
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/deepseek-rag/logs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: deepseek-rag-cache-pv
  labels:
    type: local
    app: deepseek-rag
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/deepseek-rag/cache
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: deepseek-rag-uploads-pv
  labels:
    type: local
    app: deepseek-rag
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/deepseek-rag/uploads
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-data-pv
  labels:
    type: local
    app: ollama
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/ollama
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-pv
  labels:
    type: local
    app: redis
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deepseek-rag-logs-pvc
  namespace: deepseek-rag
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: deepseek-rag
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deepseek-rag-cache-pvc
  namespace: deepseek-rag
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: deepseek-rag
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deepseek-rag-uploads-pvc
  namespace: deepseek-rag
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      app: deepseek-rag
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data-pvc
  namespace: deepseek-rag
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      app: ollama
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
  namespace: deepseek-rag
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: redis